import * as React from "react";
import Head from "next/head";

import { useRouter } from "next/router";
import { useChat } from "@/useChat";
import { AIConversation } from "@/components/AIConversation";

// const { useChat } = generateAIHooks();

export default function Home() {
  const router = useRouter();
  const props = useChat({
    onSessionCreate(sessionId) {
      if (sessionId) {
        router.replace(`/chat/${sessionId}`);
      }
    },
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AIConversation {...props} />
    </>
  );
}
