import * as React from "react";
import Head from "next/head";

import { generateClient } from "aws-amplify/data";
import type { Schema } from "@/amplify/data/resource"; // Path to your backend resource definition
import { useRouter } from "next/router";

const client = generateClient<Schema>();

export default function Home() {
  const router = useRouter();

  React.useEffect(() => {
    client.models.Conversation.observeQuery().subscribe({
      next: (results) => {
        // setConversations(results.items);
        console.log(results);
      },
    });
  }, []);

  const handleClick = async () => {
    const convo = await client.models.Conversation.create({});
    router.push(`/chat/${convo.data.id}`);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handleClick}>Click me</button>
    </>
  );
}
